# DATA ENGINEERING LIFECYCLE

Data scientists often use or start with data that is already available either in csv, format, an API, dashboard etc, but in real production environment, that data doesn't just appear but it goes through a process for it to be available. That process is called **Data Engineering Lifecycle**.<br>

This process is essential to a data scientist since the quality of your data determines the quality of your analysis and the quality of performance of your models.<br>

Data engineering lifecycle has the following connected steps:
- Data Generation
- Data Storage
- Data Ingestion
- Data Transformation
- Data Serving

1. **Data Generation** -> is point where data is captured or generated. Data can be generated using: web scraping, POS, surveys, IOT, mobile apps etc<br>

2. **Data Storage** -> This is saving data that you generated in an organised manner once it has been cleaned.<br>

3. **Data Ingestion** -> Process of loading data or putting data into a system.<br>

4. **Data Transformation** -> Its the process of preparing raw data. It may include: cleaning, removing duplicates, nulls, outliers, filtering, aggregating, merging etc

5. **Data Serving** -> Making your data available. Serving is done through APIs, end-user applications, dashboards, reports

## DATA ENGINEERING LIFECYCLE WITH PYTHON

Python plays a major role in data engineering using tools like pandas and numpy.<br>
These tools help python in reading files, cleaning and transforming data for analysis.<br>
Pandas is essential for manipulating data: Reading files, cleaning, ingestion, transformation and analysis.<br>
Numpy is good for data generation.<br>

### Data Generation
Simulate sensor data

In [85]:
import numpy as np
import pandas as pd
np.random.seed(23)

sensor_temp_data = np.random.uniform(15,35, (10, 5))
print(sensor_temp_data)

[[25.34595768 33.93925208 30.30919519 20.64791688 19.42090727]
 [28.7244417  18.34278406 22.84884933 27.36104695 23.2386019 ]
 [15.04929762 32.68064365 32.69895077 21.00819379 26.7916373 ]
 [34.56853832 31.90187644 16.30150878 20.89488929 20.75868882]
 [31.44932678 27.52366076 17.20955428 15.01057622 33.84332466]
 [17.83001515 23.43193052 21.9297888  32.39570169 23.57203625]
 [31.57502969 29.35703676 17.38453388 26.92768345 17.59512595]
 [16.55068183 31.62410511 24.2877123  18.24024958 25.95950584]
 [26.76971644 30.47226338 28.11690916 26.15413519 18.56494533]
 [19.81167062 25.12109265 22.93491398 24.66110371 34.11479682]]

### DATA STORAGE

In [86]:
df = [
    {
        "morning": [23,34,21,20,14],
        # "morning": np.random.randint(6)
        "mid_day": [32,23,12,25,17],
        "evening": [12,10,23,19,20]
    }
]
df1 = pd.DataFrame(df)
df1.to_csv("temp_data.csv", index=False)

### DATA INGESTION

In [87]:
pd.read_csv("temp_data.csv").head()

                morning               mid_day               evening
0  [23, 34, 21, 20, 14]  [32, 23, 12, 25, 17]  [12, 10, 23, 19, 20]

In [88]:
pd.read_csv("temp_data.csv").shape

(1, 3)

In [89]:
df1.shape

(1, 3)

### DATA TRANSFORMATION

In [ ]:
df_melted = df1.melt(value_vars=['morning', 'mid_day', 'evening'], \
                    var_name='Time_of_day', value_name='Temperatures')

# unnest the temperatures lis column
df_unnested = df_melted.explode('Temperatures')

# convert temperatures columns to numeric

df_unnested['Temperatures'] = pd.to_numeric(df_unnested['Temperatures'])

df_unnested.head()

  Time_of_day  Temperatures
0     morning            23
0     morning            34
0     morning            21
0     morning            20
0     morning            14

### DATA SERVING
putting data in a format that is end-user friendly

In [ ]:
df1.to_csv("temp_data_cleaned.csv", index=False)

DATA PIPELINE

In [ ]:
# Step1: Data Generation
 
students = pd.DataFrame({
    "names": ['Steve', 'Reginah', 'Grace', 'Joel'],
    "scores": [56,781,45,np.nan]
})

# Step2: Data storage

students.to_csv("students_info.csv", index=False)

# Step3: Data Ingestion
# Reading into memory
df_students = pd.read_csv("students_info.csv")

# Step4: Data Transformation
df_students['scores'] = df_students['scores'].replace(781, 78)
df_students['scores'].replace(781,78)
df_students['scores'] = df_students['scores'].fillna(df_students['scores'].mean())
df_students

     names     scores
0    Steve  56.000000
1  Reginah  78.000000
2    Grace  45.000000
3     Joel  59.666667

### DATA SERVING

In [ ]:
df_students.to_csv("clean_student_data.csv", index=False)