In [2]:
# how to establish a conecction
#1. import sqlite3
#2. import pandas(to display the item in a tabular format.)
#3. call the connection path

In [3]:
import sqlite3
import pandas as pd

conn = sqlite3.connect("bookstore.db")

print(conn)

<sqlite3.Connection object at 0x00000210A2FF07C0>

In [4]:
# using cursor
cur = conn.cursor()
cur.execute("SELECT * FROM books")
results = cur.fetchall()# it will give us a tuple of all the books
print(results)

[(1, 'Things Fall Apart', 1, 'Literary Fiction', 12.99, 45, 1958), (2, 'Arrow of God', 1, 'Literary Fiction', 11.99, 30, 1964), (3, 'A Grain of Wheat', 2, 'Historical Fiction', 13.99, 20, 1967), (4, 'Petals of Blood', 2, 'Political Fiction', 14.99, 15, 1977), (5, 'Purple Hibiscus', 3, 'Literary Fiction', 13.5, 60, 2003), (6, 'Half of a Yellow Sun', 3, 'Historical Fiction', 14.5, 55, 2006), (7, 'Americanah', 3, 'Contemporary Fiction', 15.99, 40, 2013), (8, "Death and the King's Horseman", 4, 'Drama', 10.99, 25, 1975), (9, 'Our Sister Killjoy', 5, 'Literary Fiction', 11.5, 18, 1977), (10, 'Second Class Citizen', 6, 'Literary Fiction', 12.5, 22, 1974), (11, 'African Psycho', 7, 'Thriller', 13.0, 35, 2003), (12, 'We Need New Names', 8, 'Literary Fiction', 14.0, 28, 2013), (13, 'Open City', 9, 'Literary Fiction', 13.5, 33, 2011), (14, 'The River Between', 2, 'Literary Fiction', 10.99, 12, 1965), (15, 'Weep Not Child', 2, 'Literary Fiction', 10.5, 10, 1964)]

In [5]:
# exploring database: listing all the tables in  our database
pd.read_sql("SELECT name FROM  sqlite_master WHERE type = 'table';",
            conn
)

        name
0    authors
1      books
2  customers
3     orders

In [6]:
#  geting authors
pd.read_sql("SELECT * FROM authors",
            conn)

   author_id                      name   country  birth_year
0          1             Chinua Achebe   Nigeria        1930
1          2         Ngũgĩ wa Thiong'o     Kenya        1938
2          3  Chimamanda Ngozi Adichie   Nigeria        1977
3          4              Wole Soyinka   Nigeria        1934
4          5             Ama Ata Aidoo     Ghana        1942
5          6            Buchi Emecheta   Nigeria        1944
6          7           Alain Mabanckou     Congo        1966
7          8         NoViolet Bulawayo  Zimbabwe        1981
8          9                 Teju Cole   Nigeria        1975
9         10             Mariam Konate      Mali        1985

In [7]:
# renaming using AS(aliases): create temporary display names
pd.read_sql("""
        SELECT
            title AS book_title,
            price AS price_usd
        FROM books;




""",conn)

                       book_title  price_usd
0               Things Fall Apart      12.99
1                    Arrow of God      11.99
2                A Grain of Wheat      13.99
3                 Petals of Blood      14.99
4                 Purple Hibiscus      13.50
5            Half of a Yellow Sun      14.50
6                      Americanah      15.99
7   Death and the King's Horseman      10.99
8              Our Sister Killjoy      11.50
9            Second Class Citizen      12.50
10                 African Psycho      13.00
11              We Need New Names      14.00
12                      Open City      13.50
13              The River Between      10.99
14                 Weep Not Child      10.50

In [12]:
# select author and from authors table give name an alias of author_name
pd.read_sql("""
        SELECT
            name AS author_name
        FROM authors;


""",conn)

                author_name
0             Chinua Achebe
1         Ngũgĩ wa Thiong'o
2  Chimamanda Ngozi Adichie
3              Wole Soyinka
4             Ama Ata Aidoo
5            Buchi Emecheta
6           Alain Mabanckou
7         NoViolet Bulawayo
8                 Teju Cole
9             Mariam Konate

In [13]:
# AND & OR (combining conditions)
pd.read_sql("""
   SELECT title, genre, price
   FROM books
   WHERE genre = 'Literary Fiction'        
   AND price < 12.0;
""",conn)

                title             genre  price
0        Arrow of God  Literary Fiction  11.99
1  Our Sister Killjoy  Literary Fiction  11.50
2   The River Between  Literary Fiction  10.99
3      Weep Not Child  Literary Fiction  10.50

In [ ]:
# using or
pd.read_sql("""SELECT * FROM authors WHERE birth_year>=1950 OR country= 'Kenya'

""",conn)

   author_id                      name   country  birth_year
0          2         Ngũgĩ wa Thiong'o     Kenya        1938
1          3  Chimamanda Ngozi Adichie   Nigeria        1977
2          7           Alain Mabanckou     Congo        1966
3          8         NoViolet Bulawayo  Zimbabwe        1981
4          9                 Teju Cole   Nigeria        1975
5         10             Mariam Konate      Mali        1985

In [ ]:
# pattern matching
#1. begin with #% ch%
#2. specific letter anywhere of %of%
#3. underscore_(determine the characters an item has)

In [25]:
pd.read_sql("""
        SELECT * FROM customers WHERE name LIKE '%z%';
""",conn)

,customer_id,name,email,city,country,member_since
0,5,Zanele Mokoena,zanele@email.com,Johannesburg,South Africa,2022

In [ ]:
#names with 9 characters
pd.read_sql("""
        SELECT * FROM customers WHERE name LIKE '_________';
""",conn)

   customer_id       name            email   city  country  member_since
0            4  Emeka Obi  emeka@email.com  Lagos  Nigeria          2018

In [28]:
# order by  and limit
pd.read_sql("""
        SELECT * FROM books ORDER BY price DESC, title LIMIT 6;
""",conn)

,book_id,title,author_id,genre,price,stock,published_year
0,7,Americanah,3,Contemporary Fiction,15.99,40,2013
1,4,Petals of Blood,2,Political Fiction,14.99,15,1977
2,6,Half of a Yellow Sun,3,Historical Fiction,14.50,55,2006
3,12,We Need New Names,8,Literary Fiction,14.00,28,2013
4,3,A Grain of Wheat,2,Historical Fiction,13.99,20,1967
5,13,Open City,9,Literary Fiction,13.50,33,2011

In [29]:
# aggregate function: helps group a number rows into summary numbers
# count(*)(sum), avg, min, max, round
pd.read_sql("""
        SELECT count(*) AS total_books from books;
""",conn)

   total_books
0           15

In [ ]:
# avg price of books
pd.read_sql("""
        SELECT avg(price) AS avg_price from books;
""",conn)

   avg_price
0  12.995333

In [ ]:
# rounding off ro the nearest decimal place 
pd.read_sql("""
        SELECT ROUND(avg(price),2) AS avg_price from books;
""",conn)

   avg_price
0       13.0

In [37]:
# max price of books
pd.read_sql("""
        SELECT max(price) AS max_price from books;
""",conn)

   max_price
0      15.99

In [38]:
# min price of books
pd.read_sql("""
        SELECT min(price) AS min_price from books;
""",conn)

   min_price
0       10.5

In [40]:
# sum price of books
pd.read_sql("""
        SELECT sum(price) AS sum_price from books;
""",conn)

   sum_price
0     194.93